// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOc25XzZIGXBP4HAYA6hrMZvIsypR2HA',
    appId: '1:232096831360:web:c2efe4cd4570836acbd365',
    messagingSenderId: '232096831360',
    projectId: 'hackunt-42636',
    authDomain: 'hackunt-42636.firebaseapp.com',
    storageBucket: 'hackunt-42636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vP79nZSX14Uv8llApIlAqBb3tq3-SEM',
    appId: '1:232096831360:android:8e002f0e0371c346cbd365',
    messagingSenderId: '232096831360',
    projectId: 'hackunt-42636',
    storageBucket: 'hackunt-42636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9RP8ApUVQD2WL0CPHiGVYMOhp-JUdQg',
    appId: '1:232096831360:ios:95518618dec7bb96cbd365',
    messagingSenderId: '232096831360',
    projectId: 'hackunt-42636',
    storageBucket: 'hackunt-42636.appspot.com',
    iosBundleId: 'com.example.hacktinder',
  );
}
